apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: ${ip_private}
  bindPort: 6443
nodeRegistration:
  kubeletExtraArgs:
    node-ip: ${ip_private}
    cloud-provider: external
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
networking:
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/16
apiServer:
  certSANs:
    - ${ip_private}
    - ${ip_public}
