apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
nodeRegistration:
  kubeletExtraArgs:
    node-ip: ${ip_private}
    cloud-provider: external
controlPlane:
  localAPIEndpoint:
    advertiseAddress: ${ip_private}
    bindPort: 6443
  certificateKey: ${upload_certs}
discovery:
  bootstrapToken:
    token: ${create_token}
    apiServerEndpoint: ${ip_apiserver}:6443
    caCertHashes:
      - ${cacert_hash}
